name: gazpromconnectweb
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_datetime_picker: ^1.3.4
  firebase: ^7.2.1
  image: ^2.1.4
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.6
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  fluttertoast: ^3.1.3
  sticky_headers: ^0.1.8
  image_picker: ^0.6.3
  firebase_image: ^0.1.5
  table_calendar: ^2.2.2
  flutter_sticky_header: ^0.4.0
  photo_view: ^0.9.1
  date_format: ^1.0.8
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.1
  shared_preferences: 0.5.6+1
  intl: ^0.16.1

  simple_animations: ^1.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  fonts:
    - family: Helious
      fonts:
        - asset: fonts/heliousreg.ttf
    - family: HeliousBold
      fonts:
        - asset: fonts/heliosbold.ttf
    - family: DinPro
      fonts:
        - asset: fonts/DINPro.ttf
        - asset: fonts/DINPro-Medium.ttf
        - asset: fonts/DINPro-Bold.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: ProximaNovaBold
      fonts:
        - asset: fonts/proximanova-Bold.ttf
    - family: ProximaNovaRegular
      fonts:
        - asset: fonts/proximanova-Regular.ttf
  uses-material-design: true
  assets:
        - image/gazprombankbluelogo.png
        - image/gazprombankwhitelogo.png